theme_score_app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, Length


class VideoForm(FlaskForm):
    title = StringField('Video Title', validators=[DataRequired(), Length(min=1, max=164)])
    theme = StringField('Video Theme', validators=[DataRequired()])
    submit = SubmitField('Submit')

theme_score_app/__init__.py
from flask import Flask
from flask_pymongo import PyMongo

from theme_score_app.config import Config

mongo = PyMongo()


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(Config)

    mongo.init_app(app)

    from theme_score_app.main.routes import main
    from theme_score_app.errors.handlers import errors

    app.register_blueprint(main)
    app.register_blueprint(errors)

    return app

theme_score_app/main/routes.py
# from datetime import datetime

from flask import Blueprint, flash, redirect, render_template, url_for
from bson import ObjectId

from theme_score_app import mongo

from theme_score_app.main.forms import VideoForm

main = Blueprint("main", __name__)
video_db = mongo.db.videos


@main.route("/", methods=["GET", "POST"])
def home():
    form = VideoForm()
    if form.validate_on_submit():
        video_db.insert(
            {
                "title": form.title.data,
                "theme": form.theme.data,
                "thumbs_up": 0,
                "thumbs_down": 0,
            }
        )
        flash(f"Video created.!!!!!", "success")
        return redirect(url_for("main.home", videos=get_videos()))
    return render_template(
        "home.html", form=form, legend="Create Video", videos=get_videos()
    )


@main.route("/themes", methods=["GET"])
def theme_list():
    themes = video_db.aggregate(
        [
            {
                "$group": {
                    "_id": "$theme",
                    "score": {"$avg": {"$subtract": ["$thumbs_up", "$thumbs_down"]}},
                }
            },
            {"$sort": {"score": -1}},
        ]
    )
    return render_template("theme_list.html", themes=themes)


@main.route("/video/<video_id>/thumb_up")
def thumbs_up(video_id):
    try:
        video = video_db.find({"_id": ObjectId(video_id)})
        thumbs_up = video[0]["thumbs_up"] + 1
        video_db.update({"_id": ObjectId(video_id)}, {"$set": {"thumbs_up": thumbs_up}})
    except Exception:
        flash(f"Video Not Found.!!!!!", "warning")

    return redirect(url_for("main.home", videos=get_videos()))


@main.route("/video/<video_id>/thumb_down")
def thumbs_down(video_id):
    try:
        video = video_db.find({"_id": ObjectId(video_id)})
        thumbs_down = video[0]["thumbs_down"] + 1
        video_db.update(
            {"_id": ObjectId(video_id)}, {"$set": {"thumbs_down": thumbs_down}}
        )
    except Exception:
        flash(f"Video Not Found.!!!!!", "warning")

    return redirect(url_for("main.home", videos=get_videos()))


def get_videos():
    return video_db.find()

theme_score_app/templates/home.html
{% from "macros/form_field_macro.html" import displayFormField %}

{% extends "layout.html" %}
{% set active_page = "home" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="" novalidate>
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">{{legend}}</legend>

                <!-- diplay form field using macro -->
                {{ displayFormField(form.title) }}
                {{ displayFormField(form.theme) }}

            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
    {% for video in videos %}
        <article class="media content-section">
            <div class="media-body">
                <p class="article-content"><b>Title: </b>{{ video['title'] }}</p>
                <p class="article-content"><b>Theme: </b>{{ video['theme'] }}</p>
                <div>
                    <a href="{{ url_for('main.thumbs_up', video_id=video['_id']) }}">
                        {{ video['thumbs_up'] }} <i class="fa fa-thumbs-up"></i>
                    </a>&nbsp;&nbsp;
                    <a href="{{ url_for('main.thumbs_down', video_id=video['_id']) }}">
                        {{ video['thumbs_down'] }} <i class="fa fa-thumbs-down"></i>
                    </a>
                </div>
            </div>
        </article>
    {% endfor %}
{% endblock content %}

theme_score_app/templates/layout.html
<!DOCTYPE html>
<html>

    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="theme-color" content="#000000" />

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}"> 
        <title>Theme-Score</title>
    </head>

    <body>
        <header class="site-header">
            <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
                <div class="container">
                    <a class="navbar-brand mr-4" href="/">Theme-Score</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
                    <div class="collapse navbar-collapse" id="navbarToggle">
                        <div class="navbar-nav mr-auto">
                            <a class="nav-item nav-link {{'active' if active_page == 'home'}}" href="{{ url_for('main.home') }}">Home</a>
                            <a class="nav-item nav-link {{'active' if active_page == 'theme_list'}}" href="{{ url_for('main.theme_list') }}">Themes</a>
                        </div>
                    </div>
                </div>
            </nav>
        </header>
        <main role="main" class="container">
            <div class="row">
                <div class="col-md-2"></div>
                <div class="col-md-8">
                    {% with messages = get_flashed_messages(with_categories=true) %} {% if messages %} {% for category, message in messages %}
                    <div class="alert alert-{{ category }}">
                        {{ message }}
                    </div>
                    {% endfor %} {% endif %} {% endwith %} {% block content %}{% endblock %}
                </div>
                <div class="col-md-2"></div>
            </div>
        </main>


        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body>
</html>

theme_score_app/templates/macros/form_field_macro.html
{% macro displayFormField(field) %}
    <div class="form-group">
        {{ field.label(class="form-control-label") }}

        {% if field.errors %}
            {{ field(class="form-control form-control-sm is-invalid") }}
            <div class="invalid-feedback">
                {% for error in field.errors %}
                    <span>{{ error }}</span>
                {% endfor %}
            </div>
        {% else %}
            {{ field(class="form-control form-control-sm") }}
        {% endif %}
    </div>
{% endmacro%}

theme_score_app/templates/theme_list.html
{% extends "layout.html" %}
{% set active_page = "theme_list" %}

{% block content %}
<div class="table-responsive-sm">
<h5 class="text-center">Theme List</h5>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Theme</th>
      <th>Score</th>
    </tr>
  </thead>
  <tbody>
    {% for theme in themes %}
    <tr>
      <td class="article-content">{{ theme['_id'] }}</td>
      <td class="article-content">{{ theme['score'] }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
</div>
{% endblock content %}